package com.alexismoraportal.todoapp.utils

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.ui.graphics.vector.ImageVector

/**
 * A comprehensive list of icon options for tasks.
 */
val iconOptions: List<ImageVector> = listOf(
    // Your original icons
    Icons.Filled.Android,
    Icons.Filled.Warning,
    Icons.Filled.Star,
    Icons.Filled.Adjust,
    Icons.Filled.AirplanemodeActive,
    Icons.Filled.Deck,
    Icons.Filled.Report,
    Icons.Filled.AccessTime,
    Icons.Filled.AddLocation,
    Icons.Filled.AddLink,
    Icons.Filled.Computer,
    Icons.Filled.DirectionsCar,
    Icons.Filled.AccountBox,
    Icons.Filled.AccountCircle,
    Icons.Filled.Accessibility,
    Icons.Filled.Add,
    Icons.Filled.AddAPhoto,
    Icons.Filled.AddAlarm,
    Icons.Filled.AddShoppingCart,
    Icons.Filled.AirportShuttle,
    Icons.Filled.AllInbox,
    Icons.Filled.ArrowBack,
    Icons.Filled.ArrowForward,
    Icons.Filled.AutoAwesome,
    Icons.Filled.BatteryAlert,
    Icons.Filled.BeachAccess,
    Icons.Filled.Block,
    Icons.Filled.Build,
    Icons.Filled.Cached,
    Icons.Filled.Camera,
    Icons.Filled.Cancel,
    Icons.Filled.Check,
    Icons.Filled.Close,
    Icons.Filled.Cloud,
    Icons.Filled.Dashboard,
    Icons.Filled.Delete,
    Icons.Filled.Done,
    Icons.Filled.Email,
    Icons.Filled.Favorite,
    Icons.Filled.Filter,
    Icons.Filled.Home,
    Icons.Filled.Info,
    Icons.Filled.Language,
    Icons.Filled.Lightbulb,
    Icons.Filled.Lock,
    Icons.Filled.Map,
    Icons.Filled.Menu,
    Icons.Filled.Navigation,
    Icons.Filled.NotificationImportant,
    Icons.Filled.OpenInBrowser,
    Icons.Filled.Person,
    Icons.Filled.Phone,
    Icons.Filled.Print,
    Icons.Filled.Refresh,
    Icons.Filled.Save,
    Icons.Filled.Search,
    Icons.Filled.Send,
    Icons.Filled.Settings,
    Icons.Filled.Share,
    Icons.Filled.ShoppingCart,
    Icons.Filled.ThumbUp,
    Icons.Filled.TrendingUp,
    Icons.Filled.Visibility,
    Icons.Filled.Work
)
